[package]
name = 'diagnostic'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[dependencies]
serde = { version = '', features = ['derive'] }
serde_json = ''
